name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in Git Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login https://index.docker.io/v1/ --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - uses: actions/checkout@v4
      - name: Build and tag image
        run: docker build -t ${{ github.repository }}:latest -f Dockerfile .

      - name: Push image to Git Hub
        run: |
          docker push ${{ github.repository }}:latest
  
