name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in Git Hub
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io --username ${{ secrets.GIT_USERNAME }} --password-stdin

      - uses: actions/checkout@v4
      - name: Build and tag image
        run: docker build -t ghcr.io/${{ github.repository | lower }}:latest -f Dockerfile .


      - name: Push image to Git Hub
        run: |
          docker push ${{ github.repository }}:latest
  
